name: cjp
description: 怪レい日本语
publish_to: none

version: 1.0.0-beta2

environment:
  sdk: ">=3.0.0-0.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  package_info_plus: ^3.0.2
  share_plus: ^6.3.0
  tuple: ^2.0.1
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/cjp.js/dict/

flutter_icons:
  image_path: assets/icon.png
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icon_fg.png
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
